import asyncio
import os
import shutil
import subprocess
import time
from pathlib import Path
from mantis.evaluation.evaluators import TraceEvaluator

class CampaignManager:
    def __init__(self, campaign_dir: str):
        self.campaign_dir = Path(campaign_dir)
        self.timestamp = int(time.time())
        self.output_dir = Path("run_artifacts") / f"campaign_run_{self.timestamp}"

    async def execute_campaign(self):
        if not self.campaign_dir.exists() or not self.campaign_dir.is_dir():
            print(f"❌ Campaign directory not found: {self.campaign_dir}")
            return

        self.output_dir.mkdir(parents=True, exist_ok=True)
        configs = list(self.campaign_dir.glob("*.yaml")) + list(self.campaign_dir.glob("*.yml"))
        
        # Exclude benchmark configs to only run attacks in campaign
        configs = [c for c in configs if "benchmark" not in c.name]
        
        print(f"🚀 Starting Campaign Execution. Found {len(configs)} configs.")
        print(f"📁 Output Directory: {self.output_dir}")
        print("-" * 50)

        for idx, config_path in enumerate(configs, 1):
            print(f"[{idx}/{len(configs)}] Running {config_path.name}...")
            
            # Execute synchronously to ensure deterministic traces
            process = await asyncio.create_subprocess_exec(
                "mantis", "--run", str(config_path),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await process.communicate()
            
            if process.returncode != 0:
                print(f"❌ Error running {config_path.name}")
                print(stderr.decode())
            else:
                print(f"✅ Finished {config_path.name}")
                
        print("-" * 50)
        print("🎯 Campaign Execution Complete.")
        
        # We need to aggregate the artifacts that were dumped to run_artifacts/<config_name>
        # into our campaign output dir
        for config_path in configs:
            run_name = config_path.stem
            source_dir = Path("run_artifacts") / run_name
            if source_dir.exists() and source_dir.is_dir():
                dest_dir = self.output_dir / run_name
                shutil.copytree(source_dir, dest_dir, dirs_exist_ok=True)

        print(f"📊 Run `mantis --report {self.output_dir}` to view results.")

    def generate_report(self):
        if not self.output_dir.exists():
            print(f"❌ Campaign output directory not found: {self.output_dir}")
            return

        print("\n# 🛡️ MANTIS Security Campaign Report")
        print(f"**Directory**: `{self.output_dir}`\n")
        
        print("| Experiment | Completeness | Correctness | Status |")
        print("|------------|--------------|-------------|--------|")
        
        for run_dir in self.output_dir.iterdir():
            if not run_dir.is_dir():
                continue
                
            evaluator = TraceEvaluator(str(run_dir))
            results = evaluator.evaluate_all()
            
            if "error" in results:
                print(f"| {run_dir.name} | N/A | N/A | ❌ ERR |")
                continue
                
            comp_score = results.get("trace_completeness", {}).get("score", 0.0)
            corr_score = results.get("tool_use_correctness", {}).get("score", 0.0)
            
            status = "✅ PASS" if (comp_score == 1.0 and corr_score == 1.0) else "⚠️ FAIL"
            
            print(f"| {run_dir.name} | {comp_score:.1f} | {corr_score:.1f} | {status} |")
        
        print("\n*Generated by the MANTIS CLI*")
