"""Zero Trust enforcement plugin (Post-Paper Extension, coding plan §11).

A concrete PolicyPlugin (mantis.plugins.policies.PolicyPlugin) enforcing a
policy generated by policy_generator.py, at the "tool" control point --
registered into MANTIS's existing HookBus through the identical
apply(ctx) -> HookResult contract every attack and guardrail plugin
already uses (see mantis.plugins.policies.amount_limit_guardrail for the
MANTIS-shipped analog). This plugin itself lives entirely outside
src/mantis, and MANTIS's own code never imports it -- importing *this*
module is what makes it available, via a self-registration into the same
process-global plugin_registry every other plugin registers into (see the
bottom of this file), so a config's `policies:` list can reference it by
name ("zero_trust_enforcement") exactly like any MANTIS-shipped plugin,
with zero changes to mantis.core, mantis.hooks, or the banking modules.

This plugin's own enforcement logic (default-deny by domain, in-process,
unsigned) is intentionally minimal -- a real deployment would swap it for
a thin PolicyPlugin that calls out to a real signed PDP instead, such as
Task 4 of the independently-developed
github.com/smartsystemslab-uf/Citi_P3_Zero_Trust_Backplane for this same
testbed (see README.md in this directory for how the two relate);
apply(ctx) -> HookResult is the seam where that swap happens, unchanged.
"""
from mantis.hooks import HookContext, HookAction, HookResult
from extensions.zero_trust.policy_generator import generate_default_deny_policy


class ZeroTrustEnforcementPlugin:
    name = "zero_trust_enforcement"
    supported_stages = {"tool"}

    def __init__(self, policy: dict = None, **kwargs):
        # Regenerated fresh from the live inventory when no policy is
        # passed explicitly -- consistent with the rest of MANTIS's
        # "introspected live, never a stale hand-maintained list" stance
        # (see mantis --inventory). A config's `policies:` entry for this
        # plugin can therefore be parameter-free.
        self.policy = policy or generate_default_deny_policy()
        self._always_allowed = set(self.policy.get("always_allowed_tools", []))
        self._agent_domain: dict[str, str] = {}
        for domain, data in self.policy.get("domains", {}).items():
            for agent in data.get("agents", []):
                self._agent_domain[agent] = domain

    def apply(self, ctx: HookContext) -> HookResult:
        if ctx.metadata.get("specific_hook") != "before_tool":
            return HookResult(action=HookAction.CONTINUE)

        tool_name = ctx.target
        agent_name = ctx.source
        if not tool_name or tool_name in self._always_allowed:
            return HookResult(action=HookAction.CONTINUE)

        domain = self._agent_domain.get(agent_name)
        if domain is None:
            return HookResult(
                action=HookAction.DENY,
                payload={"error": f"zero_trust: agent '{agent_name}' not recognized by the generated policy; default-deny"},
            )

        allowed = set(self.policy["domains"][domain].get("allowed_tools", []))
        if tool_name not in allowed:
            return HookResult(
                action=HookAction.DENY,
                payload={
                    "error": (
                        f"zero_trust: agent '{agent_name}' (domain '{domain}') is not "
                        f"permitted to call '{tool_name}' -- not in that domain's inventory"
                    )
                },
            )
        return HookResult(action=HookAction.CONTINUE)


# Self-registration: makes "zero_trust_enforcement" resolvable through the
# exact same plugin_registry.get(...) lookup cli/main.py already uses for
# every other attack/policy plugin -- conditional on this module actually
# being imported first (see extensions/zero_trust/run_with_zero_trust.py),
# which is the whole point: MANTIS never imports this on its own.
from mantis.core.registry import plugin_registry  # noqa: E402

try:
    plugin_registry.register("zero_trust_enforcement", ZeroTrustEnforcementPlugin)
except ValueError:
    pass  # already registered -- this module was imported more than once
